### PR TITLE
Feat/add ts types

### PR DESCRIPTION
**Pull request by no-chris**

### CODE REVIEW

**Comment by Marr11317** [comment]
Thanks for this, I am currently using a custom version of your lib where I have built typescript types and ended up with a similar fix: extracting the parser and renderer options into a new type: chordParserOptions and ChordRendererOptions.
However, we still end up with all those unnecessary files here. It might be a better option to simply ship a custom `.d.ts` file with the bare minimum. It will have to be kept up to date, though.

**Comment by no-chris** [comment]
Yes I'm still thinking about this and for now my conclusion is that auto-generation of the strictly necessary files is difficult if not impossible. 
So I'm thinking of a way to make this the least painful possible, with a mix of auto and manual. Since the public API should be pretty stable that would not be that painful to update once in a while.

**Comment by no-chris** [comment]
Here it is, from a total typescript n00b perspective it seems to work fine when I test it locally, with decent autocompletion. 

I have 2 questions though:
- is it normal that I need to explicitly import `Chord` in order to type a parameter?
- I don't see the parameters description anywhere in my IDE, is that supported at all or not?

Otherwise it looks pretty cool:

Screenshot 2020-10-20 at 23 38 15

**Comment by Marr11317** [comment]
>     * is it normal that I need to explicitly import `Chord` in order to type a parameter?

I am not sure I get what you mean here. If you want to reference the Chord type, you will need to import it. If it's just about checking its attributes, you should not have to.



>     * I don't see the parameters description anywhere in my IDE, is that supported at all or not?

I don't know about PHP storm, but I get them here in vscode.
image

**Comment by Marr11317** [comment]
btw, I had fun yesterday with your lib:
image

I'll make a PR for the demo site when it's done

**Comment by no-chris** [comment]
Looks good then, thanks for trying it out, will merge this soon 👍 


> btw, I had fun yesterday with your lib:
> image
> 
> I'll make a PR for the demo site when it's done

Nice! Looks like you are using the old demo site though?
https://chord-symbol.netlify.app/
https://github.com/no-chris/chord-symbol-demo

**Pull request merged**
