### PR TITLE
add alt modifier

### PR DESCRIPTION
**Pull request by Marr11317**
image

And the json output:
```
{
    "input": {
        "symbol": "G7alt",
        "rootNote": "G",
        "descriptor": "7alt",
        "parsableDescriptor": "7alt"
    },
    "normalized": {
        "intervals": [
            "1",
            "3",
            "#5",
            "b7",
            "b9",
            "#9",
            "#11",
            "b13"
        ],
        "semitones": [
            0,
            4,
            8,
            10,
            13,
            15,
            18,
            20
        ],
        "intents": {
            "major": true,
            "eleventh": false
        },
        "rootNote": "G",
        "quality": "dominant7",
        "isSuspended": false,
        "extensions": [],
        "alterations": [
            "#5",
            "b9",
            "#9",
            "#11",
            "b13"
        ],
        "adds": [],
        "omits": []
    },
    "formatted": {
        "rootNote": "G",
        "descriptor": "7",
        "chordChanges": [
            "#5",
            "b9",
            "#9",
            "#11",
            "b13"
        ]
    }
}
```

### CODE REVIEW

**Comment by Marr11317** [comment]
and I ran eslint, but got a bunch of errors concerning ends of files:
```
error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
```

`eslint --fix` fixes those, but modified 43 files.
Do you want a second commit with this linting?
Do I add

**Comment by Marr11317** [comment]
Should the default rendering be `G7alt` and the alternate `G7(#5,b9,#9,#11,b13)`?

**Comment by Marr11317** [comment]
> > I would personally opt for the fully-fledged 7(b5b9#9#11b13)
> 
> On which rationale?

Because I like clarity and do not appreciate the sounding of a 9 in a #9 context.

> 
> And if one enters `7(b5b9#9#11b13)` would you expect it to be rendered as `alt.`?

See above picture. Currently, `alt` is the alternate, not the default. Not sure about that default though.

> What would be the result of parsing `C9alt.`?
Even though it is technically incorrect (and as such should return `null`), it currently does this:
image

> Just exploring ideas, we could allow some degrees of configuration here, from 0 intervals parsing, just parsing and rendering the string `alt` to some specific intervals parsing.

This might be part of a greater question: should these be configurable?
https://github.com/no-chris/chord-symbol/blob/master/src/renderer/filters/simplify.js#L21

**Comment by no-chris** [comment]
Thanks a lot for this PR.

First I need to brush up my theory to make sure I get the requirements straight. Do you agree with the information on this page or do you have a more reliable source to share? https://en.wikipedia.org/wiki/Altered_chord
It can be a book.

Thanks

**Comment by no-chris** [comment]
>This might be part of a greater question: should these be configurable?
>https://github.com/no-chris/chord-symbol/blob/master/src/renderer/filters/simplify.js#L21

It does make perfect sense indeed

**Comment by Marr11317** [comment]
> Do you agree with the information on this page or do you have a more reliable source to share? https://en.wikipedia.org/wiki/Altered_chord#Alt_chord

Looks good to me.

**Comment by Marr11317** [comment]
Regarding theory, you can see the altered chords as a chord containing all the notes in the melodic minor scale a semitone above the root.
For example, A `B7alt` chord contains all the notes in the `Cmelodic minor` scale.

**Comment by no-chris** [comment]
I did the API change. Since it's a breaking change, let's work first in a separate branch so I can prepare the release properly with a migration guide:
https://github.com/no-chris/chord-symbol/tree/v1.0.0

**Comment by Marr11317** [comment]
Sorry to keep you waiting, I didn't have the time to work on this in the two last weeks. I hope get this done by next weekend (not this one coming though).

**Comment by no-chris** [comment]
I'm going to close this since I've picked up your job in https://github.com/no-chris/chord-symbol/pull/253

I think that is a cool feature, thanks for the input.

**Pull request closed without merging**
